<template>
  <div id="app">
      <AppHeader/>
      <AppMain/>
      <AppFooter/>
  </div>
</template>

/* -------------------------------------------------------------------------- */

<script>
//---------------components-------------------
import AppHeader from './components/AppHeader.vue';
import AppMain from './components/AppMain.vue';
import AppFooter from './components/AppFooter.vue';
//--------------------------------------------
export default {
    name: '',
    components: {
        AppHeader,
        AppMain,
        AppFooter,
    },
    data() {
        return {
            CardsCategory:[
                {
                    name:'All Categories'
                },
                {
                    name:'Business'
                },
                {
                    name:'Design'
                },
                {
                    name:'IT & Software'
                },
                {
                    name:'Lifestyle'
                },
                {
                    name:'Marketing'
                },
                {
                    name:'Office Productivity'
                },
            ],
            Cards:[
                {
                    image:'1',
                    category:'',
                    course_name:'',
                    vote:'',
                    old_price:'',
                    new_price:'',
                },
                {
                    image:'2',
                    category:'',
                    course_name:'',
                    vote:'',
                    old_price:'',
                    new_price:'',
                },
                {
                    image:'3',
                    category:'',
                    course_name:'',
                    vote:'',
                    old_price:'',
                    new_price:'',
                },
                {
                    image:'4',
                    category:'',
                    course_name:'',
                    vote:'',
                    old_price:'',
                    new_price:'',
                },
                {
                    image:'5',
                    category:'',
                    course_name:'',
                    vote:'',
                    old_price:'',
                    new_price:'',
                },
                {
                    image:'6',
                    category:'',
                    course_name:'',
                    vote:'',
                    old_price:'',
                    new_price:'',
                },
                {
                    image:'7',
                    category:'',
                    course_name:'',
                    vote:'',
                    old_price:'',
                    new_price:'',
                },
                {
                    image:'8',
                    category:'',
                    course_name:'',
                    vote:'',
                    old_price:'',
                    new_price:'',
                },
                {
                    image:'9',
                    category:'',
                    course_name:'',
                    vote:'',
                    old_price:'',
                    new_price:'',
                },
                {
                    image:'10',
                    category:'',
                    course_name:'',
                    vote:'',
                    old_price:'',
                    new_price:'',
                }, 
                {
                    image:'11',
                    category:'',
                    course_name:'',
                    vote:'',
                    old_price:'',
                    new_price:'',
                },
                {
                    image:'12',
                    category:'',
                    course_name:'',
                    vote:'',
                    old_price:'',
                    new_price:'',
                },
                {
                    image:'13',
                    category:'',
                    course_name:'',
                    vote:'',
                    old_price:'',
                    new_price:'',
                },
                {
                    image:'14',
                    category:'',
                    course_name:'',
                    vote:'',
                    old_price:'',
                    new_price:'',
                },
                {
                    image:'15',
                    category:'',
                    course_name:'',
                    vote:'',
                    old_price:'',
                    new_price:'',
                },
                {
                    image:'16',
                    category:'',
                    course_name:'',
                    vote:'',
                    old_price:'',
                    new_price:'',
                },   
            ],
            ExtraCards:[
                {
                    title:'',
                    text_info:'',
                    text_button:'',
                    image:'',
                },
                {
                    title:'',
                    text_info:'',
                    text_button:'',
                    image:'',
                },
            ],
            FooterSocialIcons:[
                {
                    image:'',
                    color:'',
                },
                {
                    image:'',
                    color:'',
                },
                {
                    image:'',
                    color:'',
                },
                {
                    image:'',
                    color:'',
                },
                {
                    image:'',
                    color:'',
                },
            ],
        };
    },
    methods:{},
    created(){},
    mounted(){}
} 
</script>

/* -------------------------------------------------------------------------- */

<style lang="scss">
@import './assets/variables.scss';
</style>
